org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=ApothicSpawners
modName=Apothic Spawners
modGroup=dev.shadowsoffire
modid=apothic_spawners
author=Shadows_of_Fire
desc=The Spawner Module of Apotheosis, allowing for silk-touching and modification.
version=2.0.0beta2

# Dependencies
mcVersion=26.1.2
javaVersion=25
forgeVersion=26.1.2.22-beta
jeiVersion=29.5.0.26
jadeVersion=26.0.9
#curiosVersion=9.5.1+1.21.1
placeboVersion=10.0.0-beta8
#topVersion=1.20.0-9.0.0-1
#patchouliVersion=1.19.2-76

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing
requiredDeps=placebo
#optionalDeps=
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=986583

# Tests
enableTests=false
