modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="apothic_spawners"

version="2.0.0beta2"

displayName="Apothic Spawners"

authors="Shadows_of_Fire"

description='''The Spawner Module of Apotheosis, allowing for silk-touching and modification.'''

[[mixins]]
config="apothic_spawners.mixins.json"

[[dependencies.apothic_spawners]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_spawners]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.22-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_spawners]]
    modId="placebo"
    type="required"
    versionRange="[10.0.0-beta8,)"
    ordering="NONE"
    side="BOTH"
